name: Upload Code
run-name: Uploading Python Code

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy file to s3
      run: aws s3 sync ./test/ s3://${{ secrets.BUCKET}} --exclude 'git*/*'
